import Icon from './Icon';
import { dashboardSummary, parseRecord } from '../lib/client';

export default function Dashboard({ history, products, images, loading, apiReady, onNavigate, onOpenHistory, onAddProduct }) {
  const { records, days, weekly } = dashboardSummary(history);
  const maximum = Math.max(1, ...days.map(day => day.count));
  const stats = [
    { label: 'Konten tersimpan', value: records.length, note: 'Storyboard, thread & naskah', icon: 'folder', color: 'indigo', tab: 'history' },
    { label: 'Produk di workspace', value: products.length, note: 'Siap menjadi inspirasi konten', icon: 'box', color: 'teal', tab: 'bank_storyboard' },
    { label: 'Koleksi gambar', value: images.length, note: 'Aset visual Anda', icon: 'image', color: 'amber', tab: 'bank_gambar' },
    { label: 'Konten minggu ini', value: weekly, note: 'Tersimpan dalam 7 hari terakhir', icon: 'spark', color: 'violet', tab: 'history' }
  ];
  const actions = [
    { title: 'Buat storyboard', description: 'Ubah produk jadi cerita visual.', icon: 'film', tab: 'bang_jenggot', color: 'indigo' },
    { title: 'Tulis thread', description: 'Bangun cerita yang menjual.', icon: 'text', tab: 'thread', color: 'teal' },
    { title: 'Artikel jadi konten', description: 'Susun utas dari sumber berita.', icon: 'news', tab: 'gen_thread', color: 'amber' },
    { title: 'Tambah produk', description: 'Lengkapi koleksi produk Anda.', icon: 'plus', tab: 'bank_storyboard', color: 'violet' }
  ];
  return <div className="dashboard fade-in">
    <div className="page-heading"><div><span className="eyebrow">OVERVIEW</span><h1>Ruang untuk ide besar Anda.</h1><p>Selamat datang kembali. Mari buat konten yang lebih berarti hari ini.</p></div><button className="btn-primary" onClick={() => onNavigate('bang_jenggot')}><Icon name="plus" size={18} />Buat konten</button></div>
    <section className="dashboard-hero"><div><span className="hero-kicker"><span /> CREATOR STUDIO</span><h2>Dari satu produk,<br />jadi banyak cerita.</h2><p>Satukan ide, aset, dan kekuatan AI untuk mempercepat proses kreatif Anda.</p><button onClick={() => onNavigate('bang_jenggot')} className="hero-button">Mulai berkreasi <Icon name="arrow" size={18} /></button></div><div className="hero-art" aria-hidden="true"><div className="art-orbit" /><div className="art-card art-card-back"><Icon name="text" size={28} /><i /><i /></div><div className="art-card art-card-front"><div className="art-scene"><Icon name="film" size={42} /></div><span>YOUR NEXT GREAT STORY</span><div className="art-timeline"><i /><i /><i /></div></div><div className="art-spark"><Icon name="spark" size={23} /></div></div></section>
    <section className="stats-grid" aria-label="Statistik workspace">{stats.map(stat => <button className="stat-card" key={stat.label} onClick={() => onNavigate(stat.tab)}><div className="stat-top"><span>{stat.label}</span><span className={`icon-tile ${stat.color}`}><Icon name={stat.icon} size={20} /></span></div><strong>{loading ? '—' : stat.value}</strong><small>{stat.note}</small></button>)}</section>
    <section className="quick-section"><div className="section-heading"><div><h2>Mulai dari sini</h2><p>Alat yang tepat untuk setiap ide.</p></div><span className="section-caption">PILIH ALUR KREATIF ANDA</span></div><div className="quick-actions-row">{actions.map(action => <button key={action.title} className="quick-action-btn" onClick={action.tab === 'bank_storyboard' ? onAddProduct : () => onNavigate(action.tab)}><span className={`icon-tile ${action.color}`}><Icon name={action.icon} size={23} /></span><strong>{action.title}</strong><p>{action.description}</p><Icon name="arrow" size={18} className="quick-arrow" /></button>)}</div></section>
    <div className="dashboard-bottom-grid"><section className="activity-chart surface"><div className="section-heading"><h2>Produktivitas konten</h2><span className="subtle-badge">7 hari terakhir</span></div><div className="chart-summary"><strong>{loading ? '—' : weekly}</strong><span>konten tersimpan minggu ini</span></div><div className="bar-chart" aria-label="Jumlah konten tersimpan per hari">{days.map((day, index) => <div className="chart-column" key={index}><span className="chart-count">{loading ? '—' : day.count}</span><div className="bar-track"><div className="chart-bar" style={{ height: loading ? '0%' : `${day.count / maximum * 100}%` }} /></div><span>{day.label}</span></div>)}</div><p className="chart-note">{loading ? 'Memuat aktivitas workspace...' : weekly ? 'Dihitung dari konten yang benar-benar disimpan ke database.' : 'Belum ada konten minggu ini. Karya pertama Anda dimulai dari satu ide.'}</p></section>
      <section className="recent-activity surface"><div className="section-heading"><h2>Aktivitas terbaru</h2><button className="text-button" onClick={() => onNavigate('history')}>Lihat semua <Icon name="arrow" size={15} /></button></div>{loading ? <div className="compact-empty" role="status"><span className="loading-spinner" />Memuat aktivitas...</div> : records.length ? <div className="activity-list">{records.slice(0, 4).map(item => <button className="activity-item" key={item.id} onClick={() => onOpenHistory(item)}><span className="icon-tile indigo"><Icon name={item.type?.includes('Utas') ? 'text' : 'film'} size={18} /></span><span className="activity-detail"><strong>{item.product_desc || parseRecord(item.result).name || 'Konten tanpa judul'}</strong><small>{item.type} · {new Date(item.created_at).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' })}</small></span><Icon name="arrow" size={15} /></button>)}</div> : <div className="compact-empty"><span className="empty-illustration"><Icon name="folder" size={30} /></span><h3>Belum ada aktivitas</h3><p>Konten yang Anda simpan akan muncul di sini.</p><button className="text-button" onClick={() => onNavigate('bang_jenggot')}>Buat konten pertama <Icon name="arrow" size={15} /></button></div>}<div className={`api-callout ${apiReady ? 'configured' : ''}`}><Icon name={apiReady ? 'check' : 'settings'} size={19} /><div><strong>{apiReady ? 'API Key sudah diisi' : 'Siapkan asisten AI Anda'}</strong><p>{apiReady ? 'Koneksi akan diperiksa saat membuat konten.' : 'Tambahkan API Key untuk mulai membuat konten.'}</p></div><button className="icon-button" aria-label="Buka pengaturan API" onClick={() => onNavigate('settings')}><Icon name="arrow" size={18} /></button></div></section>
    </div>
    <footer className="dashboard-footer">Creator Hub AI <span>Dirancang untuk proses kreatif yang lebih baik.</span></footer>
  </div>;
}
